// client/src/components/kundli/PredictionSection.jsx
import React, { useState, useEffect } from 'react';
import { getAIPrediction } from '../../services/ai';
import Card from '../ui/Card';
import Button from '../ui/Button';

const PredictionSection = ({ birthDetails, kundliId }) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [prediction, setPrediction] = useState(null);

  const fetchPrediction = async () => {
    setLoading(true);
    setError('');
    try {
      const data = await getAIPrediction({ birthDetails, kundliId });
      setPrediction(data);
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to fetch AI prediction');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (birthDetails || kundliId) {
      fetchPrediction();
    }
  }, [birthDetails, kundliId]);

  if (loading) {
    return <div className="text-center py-8">Generating AI insights...</div>;
  }

  if (error) {
    return (
      <div className="text-center py-8">
        <p className="text-red-600">{error}</p>
        <Button onClick={fetchPrediction} variant="outline" className="mt-2">
          Retry
        </Button>
      </div>
    );
  }

  if (!prediction) return null;

  return (
    <Card className="bg-gradient-to-r from-purple-50 to-indigo-50 p-6">
      <div className="flex items-center gap-3 mb-4">
        <span className="text-3xl">🤖</span>
        <h3 className="text-xl font-semibold">AI-Powered Prediction</h3>
      </div>
      <div className="prose max-w-none">
        <p className="text-gray-700 mb-3">{prediction.summary}</p>
        {prediction.insights && (
          <ul className="list-disc list-inside space-y-1">
            {prediction.insights.map((insight, idx) => (
              <li key={idx} className="text-gray-600">{insight}</li>
            ))}
          </ul>
        )}
      </div>
      <div className="mt-4 text-sm text-gray-500 italic">
        Generated by AI – For entertainment only.
      </div>
    </Card>
  );
};

export default PredictionSection;